services:
  mongo:
    image: mongo:latest
    container_name: mongo
    networks:
      - bayeta_net
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  bayeta:
    build: .
    container_name: bayeta
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/
    ports:
      - "5000:5000"
    networks:
      - bayeta_net

volumes:
  mongo_data:

networks:
  bayeta_net:
    driver: bridge
